from .SD3_5EmptyLatent import MISC_CLASS_MAPPINGS, MISC_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = MISC_CLASS_MAPPINGS
NODE_DISPLAY_NAME_MAPPINGS = MISC_NAME_MAPPINGS

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
