from .SD3_5EmptyLatent import MISC_CLASS_MAPPINGS as SD35_MAPPINGS
from .SD3_5EmptyLatent import MISC_NAME_MAPPINGS as SD35_NAME_MAPPINGS
from .FluxEmptyLatent import NODE_CLASS_MAPPINGS as FLUX_MAPPINGS
from .FluxEmptyLatent import NODE_DISPLAY_NAME_MAPPINGS as FLUX_NAME_MAPPINGS

# Combine all mappings
NODE_CLASS_MAPPINGS = {**SD35_MAPPINGS, **FLUX_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**SD35_NAME_MAPPINGS, **FLUX_NAME_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
